spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine_schema
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: link
profiles: link
app:
  link: https://ipfran.ru/




