spring:
  liquibase:
    enabled: true
#    change-log: db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          batch_size:  100
          batch_versioned_data:  true
        order_updates:  true
#        generate_statistics:  true

#  sql:
#    init:
#      mode: always

#server:
#  servlet:
#    context-path: /admin
app:
  sites:
#    -
#      url:  https://dombulgakova.ru/
#      name:  DomBulgakova
    -
      url: https://nikoartgallery.com/
      name: ArtGallery
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
  referrer: "http://www.google.com"
#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: TRACE
#        hicary:
#          HikariConfig: DEBUG

