spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine_schema
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
#    properties:
#      hibernate:
#        globally_quoted_identifiers: true
  profiles:
    active: link
profiles: link
app:
  link: https://ipfran.ru/




