spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine_schema
    username: root
    password: root


    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 30000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          batch_size:  50
          batch_versioned_data:  true
        order_updates:  true
        generate_statistics:  true

  sql:
    init:
      mode: always

#server:
#  servlet:
#    context-path: /admin
app:
  sites:
    -
      url:   https://nikoartgallery.com/
      name:  ArtGallery
    -
      url:  https://dombulgakova.ru/
      name:  DomBulgakova
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
  referrer: "http://www.google.com"
#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: TRACE
#        hicary:
#          HikariConfig: DEBUG

